LANGFLOW_API_DATA = '{"input_value": "", "output_type": "chat", "input_type": "chat"}'
LANGFLOW_API_URL = "<API_URL"
LANGFLOW_API_TOKEN = "<API_TOKEN>"
AI_AGENT_TITLE = "Meu agente de IA no Langflow"
AI_AGENT_DESCRIPTION = "Este é um exemplo de descrição de agente desenvolvido no LangFlow."
WELCOME_MESSAGE = "Olá! Como posso te ajudar hoje?"