LANGFLOW_API_DATA = '{"input_value": "", "output_type": "chat", "input_type": "chat"}'
LANGFLOW_API_URL = "https://api.langflow.astra.datastax.com/lf/73e42511-817c-46b7-ba2b-709a700a4aa0/api/v1/run/b39393f6-c67f-4d1f-97a1-1ed6f67b0395?stream=false"
LANGFLOW_API_TOKEN = "AstraCS:HSPogJjPhzrtcNzMURywTWUG:627efb2ed5fd6d8003738898cf849595b15aaa7a4c97684be59f2f48cec1da61"
AI_AGENT_TITLE = "Meu agente de IA no Langflow"
AI_AGENT_DESCRIPTION = "Este é um exemplo de descrição de agente desenvolvido no LangFlow."
WELCOME_MESSAGE = "Olá! Como posso te ajudar hoje?"